# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  connection-timeout: 5000
  context-path: /

spring:
  # 环境 dev|test|pro
  profiles:
    active: @env@
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  resources: # 指定静态资源的路径
    static-locations: classpath:/static/,classpath:/views/,file:${fileupload.filepath}
  redis:
    open: false  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: localhost
    port: 6379
    password:       # 密码（默认为空）
    timeout: 6000  # 连接超时时长（毫秒）
    pool:
      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10      # 连接池中的最大空闲连接
      min-idle: 5       # 连接池中的最小空闲连接
  task:
    pool:
      corePoolSize: 10 #线程池维护线程的最少数量
      maxPoolSize: 30 #线程池维护线程的最大数量
      queueCapacity: 100 #缓存队列
      keepAliveSeconds: 60 #允许的空闲时间

# Mybatis配置
mybatis:
  mapperLocations: classpath*:mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.wzlue.common.mybatis.handler
renren:
  # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5[www.renren.io]
    # token有效时长，7天，单位秒
    expire: 604800
    header: token
wechat:
  miniapp:
    appid: wx77c5ada45656a720
    secret: e199d8a71ee6bd559522e4149af48818
    token:
    aesKey:
    msgDataFormat: JSON
  pay:
    appId: wx77c5ada45656a720
    mchId: 1385804302
    mchKey: 09b6d3eb363577978008583740351167
    subAppId:
    subMchId:
    #     E:\团购小程序\cert\apiclient_key.pem
    keyPath: /home/group/cert/apiclient_key.pem
    notifyUrl: https://pxshapp.sun7y.com/app/pay/parseOrderNotifyResult
